export default {
    translation: {
      Login: {
        Title: "登陸以繼續",
        Username_or_Email: "使用者名稱或信箱",
        Password: "密碼",
        Login_Button: "登錄",
        Forgot_Password: "忘記密碼？",
        Username_or_Email_Desc: "您必須輸入一個使用者名稱或信箱。",
        Account_Password_Desc: "請輸入您的帳戶密碼。",
        Account_Incorrect: "找不到對應的帳戶。",
        Many_Attempts: "當前嘗試登陸次數過多，請稍後再試。",
        Recaptcha_Error: "無法驗證 reCAPTCHA 數據。",
        Request_Failed: "請求失敗錯誤代碼404",
        CSRF_Token: "CSRF token 不匹配。"
      },
      Reset_Password: {
        Password_Reset: "請求重設密碼",
        Email: "信箱",
        New_Password_Required: "需要一個新的密碼。",
        Password_Characters_Min: "你的密碼長度至少需要8位。",
        Password_Not_Match: "您的新密碼不匹配。",
        Account_Email: "輸入您的電子郵件地址以獲得重設密碼的方法。",
        Valid_Email: "必須提供一個合法的電子郵件以繼續。",
        Send_Email: "發送郵件",
        Return_to_Login: "返回以登錄",
        Reset_Password: "重設密碼",
        New_Password: "新密碼",
        New_Password_Desc: "密碼長度至少需要8位。",
        Confirm_New_Password: "確認新密碼",
        Send_Email_Link: "我們已經向您的信箱發送了重設密碼連結！"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "設備檢查點",
        Recovery_Code: "恢復代碼",
        Authentication_Code: "驗證碼",
        Enter_Two_Factor_Desc_1: "輸入由您的設備生成的二次身份驗證token",
        Enter_Two_Factor_Desc_2: "輸入一個當你在這個帳戶設置二次身份驗證時生成的恢復代碼以繼續。",
        Lost_Device: "我遺失了我的設備",
        Have_Device: "我找得到我的設備",
        Continue: "繼續"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "您必須提供一個驗證碼以繼續。",
        Two_Factor_Activate_Desc_2: "二次身份驗證目前已經在您的帳戶上啟用。",
        Two_Factor_Activate_Desc_3: "驗證碼必須是6位數字。",
        Two_Factor_Active_Title: "已啟用二次身份驗證",
        Two_Factor_Active_Desc_1: "二次身份驗證已經在您的帳戶上啟用。如果您無法訪問您的身份驗證設備，您需要使用下面顯示的代碼之一來訪問您的帳戶。",
        Two_Factor_Active_Desc_2: "這個代碼不會被再次顯示。",
        Two_Factor_Active_Desc_3: "請立即記下它們，並且將它們保存在安全都位置（例如密碼管理器）。",
        Two_Factor_Active_Button: "關閉",
        Two_Factor_Disabled_Desc: "您的帳戶目前沒有啟用二次身份驗證。點擊下方的按鈕來配置他。",
        Two_Factor_Disable_Desc_1: "您必須提供當前的密碼以繼續。",
        Two_Factor_Disable_Desc_2: "關閉二次身份驗證需要提供您帳戶當前的密碼。",
        Two_Factor_Disable_Title: "當前密碼",
        Two_Factor_Disable_Button: "關閉二次身份驗證",
        Two_Factor_Setup_Desc_1: "在掃描二維碼圖像後輸入由您的驗證設備提供的代碼。",
        Two_Factor_Setup_Desc_2: "或者，在您的身份驗證器應用程式中輸入以下token：",
        Two_Factor_Setup_Button: "設定",
        Two_Factor_Incorrect_Password: "提供的密碼無效。",
        Button_Disable: "禁用",
        Button_Enable: "啟用",
        Create_Api_Desc_Title: "備註描述",
        Create_Api_Desc: "一個對此API key的描述備註。",
        Create_Api_Ips_Title: "允許放行的IP",
        Create_Api_Ips_Desc: "留空以允許任意IP使用此API key,或者每行輸入一個放行的IP。",
        Create_Api_Button: "創建",
        Update_Email_Desc_1: "您必須提供當前的帳戶密碼。",
        Update_Email_Required: "必須填寫信箱",
        Update_Email_Success_Title: "成功",
        Update_Email_Success: "您的主信箱已更新。",
        Update_Email_Error_Title: "錯誤",
        Update_Email_Button: "更新信箱",
        Update_Password_Title: "新密碼",
        Update_Password_Desc_1: "您必須提供當前的密碼。",
        Update_Password_Desc_2: "密碼與您先前輸入的不一致。",
        Update_Password_Desc_3: "您的新密碼長度應至少是8位，而且僅在該網站使用。",
        Update_Password_Required: "必須填寫密碼",
        Update_Password_Button: "更新密碼",
        Update_Password_Error: "您輸入的密碼對此帳戶無效。",
        Update_Password_Min: "密碼至少需要8個字元",
        Confirm_Password: "確認密碼",
        Account_Page_Title: "帳戶概覽",
        Account_Two_Factor_Required_Title: "需要二次身份驗證",
        Account_Two_Factor_Required_Desc: "您的帳戶必須開啟二次身份驗證以繼續。",
        Account_Update_Email_Title: "更新電子郵件地址",
        Account_Setup_Two_Factor_Title: "配置二次身份驗證",
        Api_Page_Title: "帳戶API",
        Api_Create_Title: "創建API Key",
        Api_List_Title: "API Keys",
        Api_List_Loading: "載入中...",
        Api_List_Empty: "這個帳戶目前沒有API keys",
        Api_List_Used_1: "上一次使用: ",
        Api_List_Used_2: "從未使用",
        Api_Delete_Title: "確認要刪除的key",
        Api_Delete_Button: "是，刪除這個key",
        Api_Delete_Desc: "您確定您要刪除這個API key嗎？所有使用這個API key的請求都將立刻失效。",
        Api_Setup_Title: "您的API Key",
        Api_Setup_Desc: "您請求的API key如下所示。請將其保存在安全的地方，API key不會再次顯示。",
        Api_Min_Characters: "描述需要至少4個字元",
        Api_Setup_Button: "關閉",
        Api_Ip_Incorrect_1: "IP位址1必須是一個有效的IP位址。",
        Api_Ip_Incorrect_2: "IP位址2必須是一個有效的IP位址。",
        Api_Ip_Incorrect_3: "IP位址3必須是一個有效的IP位址。"
      },
      Search: {
        Search_Title: "搜索項目",
        Search_Desc_1: "請輸入至少3個字元開始搜索。",
        Search_Desc_2: "請輸入伺服器名稱，uuid，或者分配開始搜索。"
      },
      Dashboard: {
        Dash_Page_Title: "控制面板",
        Dash_Show_Server_1: "顯示其他人的伺服器",
        Dash_Show_Server_2: "顯示您的伺服器",
        Dash_Show_Server_3: "沒有其他伺服器可供顯示。",
        Dash_Show_Server_4: "沒有其他伺服器關聯到您的帳戶。"
      },
      Server_Row: {
        Server_Unlimited: "無限制的",
        Server_Suspended: "暫停中",
        Server_Connect_Error: "連接錯誤",
        Server_Transferring: "遷移中",
        Server_Installing: "安裝中",
        Server_Restoring_Backup: "恢復備份中",
        Server_Unavailable: "不可用的",
        Server_Of: "of"
      },
      Elements: {
        Elements_Cancel_Button: "取消",
        Elements_Copy_Text: "複製到剪貼板。",
        Elements_Error: "應用程式呈現此視圖時遇到了一個錯誤。嘗試刷新頁面。"
      },
      Server: {
        Server_Page_Title: "控制台",
        Server_Transfer_Console: "遷移失敗。",
        Server_Archived_Console: "伺服器已成功存檔，正在嘗試連接到目標節點..",
        Server_Send_Command: "輸入指令...",
        Server_State_Console: "伺服器創建為",
        Server_State_Starting: "啟動中",
        Server_State_Offline: "離線中",
        Server_State_Stopping: "停止中",
        Server_State_Running: "運行中",
        Server_State_Connect: "正在連接...",
        Server_State_Install: "此伺服器當前正在運行安裝程式，此時絕大部分操作不可用。",
        Server_State_Transfer: "此伺服器當前正在遷移到另一個節點，此時所有操作不可用。",
        Server_Button_Start: "啟動",
        Server_Button_Restart: "重啟",
        Server_Button_Kill: "強制停止",
        Server_Button_Stop: "停止",
        Server_Memory_Graph_Title: "記憶體使用量",
        Server_Cpu_Graph_Title: "CPU使用量",
        Server_Graph_Desc: "伺服器離線。",
        Server_Websocket_Error: "驗證由websocket提供的憑據時出錯。請刷新頁面。",
        Server_Connect_Server: "我們在連接到您的伺服器時出現了一些問題，請等待..."
      },
      Server_Backup: {
        Backup_Page_Title: "備份",
        Backup_Empty_1: "看起來我們已經展示了所有備份給您，嘗試回到上一個頁面。",
        Backup_Empty_2: "看起來您當前沒有在這個伺服器儲存任何備份。",
        Backup_Forbidden: "無法為此伺服器創建備份，因為備份限制設置為0。",
        Backup_Information: "已為此伺服器創建備份。",
        Backup_Create_Title_1: "創建伺服器備份",
        Backup_Create_Title_2: "備份名",
        Backup_Create_Title_3: "忽略的文件和目錄",
        Backup_Create_Title_4: "鎖定",
        Backup_Create_Desc_1: "如果輸入，這個名字會被用於這個備份。",
        Backup_Create_Desc_2: "輸入生成此備份時要忽略的文件或文件夾。留空使用在伺服器根目錄的.pteroignore文件的目錄（如果存在）。除了透過在路徑前添加驚嘆號來否定規則之外，還支持文件和文件夾的通配符匹配。",
        Backup_Create_Desc_3: "在這個備份被解鎖前，阻止它被刪除。",
        Backup_Create_Start_Button: "開始備份",
        Backup_Create_Button: "創建備份",
        Backup_Created_Title: "解鎖這個備份？",
        Backup_Created_Desc_1: "您確定要解鎖這個備份嗎？它將不再被保護以被防止自動或意外刪除。",
        Backup_Created_Button: "是，解鎖",
        Backup_Restore_Title: "恢復這個備份？",
        Backup_Restore_Desc_1: "這個伺服器將會停止以恢復備份。一旦開始備份，您將無法控制伺服器電源狀態，訪問檔案管理器，或者創建額外的備份直到它完成。",
        Backup_Restore_Desc_2: "您確定想要繼續嗎？",
        Backup_Restore_Desc_3: "在恢復此備份之前刪除所有文件和文件夾。",
        Backup_Restore_Button: "恢復備份",
        Backup_Delete_Title: "刪除這個備份？",
        Backup_Delete_Desc_1: "您確定想要刪除這個備份嗎？這是一個永久性操作，一旦刪除這個備份無法被恢復。",
        Backup_Delete_Button: "是，刪除這個備份",
        Backup_SubMenu_Download: "下載",
        Backup_SubMenu_Restore: "恢復",
        Backup_SubMenu_Unlock: "解鎖",
        Backup_SubMenu_Lock: "鎖定",
        Backup_SubMenu_Delete: "刪除"
      },
      Server_Databases: {
        Database_Page_Title: "資料庫",
        Database_Show_Empty: "看起來您沒有任何資料庫。",
        Database_Show_Forbidden: "無法為此伺服器創建資料庫。",
        Database_Limit_Desc: "資料庫已分配給此伺服器。",
        Database_Create_Title_1: "創建新資料庫",
        Database_Create_Title_2: "資料庫名稱",
        Database_Create_Title_3: "連接來自",
        Database_Create_Desc_1: "一個對此資料庫實例的描述。",
        Database_Create_Desc_2: "Where connections should be allowed from. Use % for wildcards.",
        Database_Create_Button_1: "創建資料庫",
        Database_Create_Button_2: "新資料庫",
        Database_Create_Error_1: "處理此請求時遇到意外錯誤，請重試。",
        Database_Create_Error_2: "必須提供一個資料庫名稱。",
        Database_Create_Error_3: "資料庫名稱至少需要3個字元。",
        Database_Create_Error_4: "資料庫名稱不能超出48個字元。",
        Database_Create_Error_5: "資料庫名稱應僅包含字母數字字元、下劃線、破折號和/或句點。",
        Database_Create_Error_6: "必須提供連接值。",
        Database_Create_Error_7: "必須提供一個有效的連接地址。",
        Database_Delete_Title_1: "確認刪除資料庫",
        Database_Delete_Title_2: "確認資料庫名稱",
        Database_Delete_Title_3: "資料庫連接詳情",
        Database_Delete_Title_4: "端點",
        Database_Delete_Title_5: "連接來自",
        Database_Delete_Title_6: "使用者名稱",
        Database_Delete_Title_7: "密碼",
        Database_Delete_Title_8: "JDBC Connection String",
        Database_Rotate_Button: "Rotate Password",
        Database_Delete_Desc_1: `刪除資料庫是一項永久性操作，不能被撤銷。這將永久刪除"{{database}}"資料庫並且刪除所有相關數據。`,
        Database_Create_Desc_2: "輸入資料庫名稱以確認刪除。",
        Database_Delete_Button: "刪除資料庫",
        Database_Delete_Error_1: "必須提供資料庫名稱。",
        Database_Delete_Error_2: "No database host was found that meets the requirements for this server."
      },
      Server_Files: {
        Files_Page_Title: "檔案管理器",
        Files_Create_Button: "新增文件",
        Files_Directory_Empty: "這個目錄看起來是空的。",
        Files_Show_Files_Max: "這個目錄過大無法在瀏覽器中完整顯示，將僅顯示前250個文件。",
        Files_Chmod_Title: "文件模式",
        Files_Chmod_Button: "上傳",
        Files_Delete_File_Or_Directory_Title: "刪除這個",
        Files_Delete_File_Or_Directory_Button: "是，刪除",
        Files_Delete_File_Or_Directory_Desc: "文件刪除是一項永久性操作，您不能撤銷這個操作。",
        Files_Delete_File: "文件",
        Files_Delete_Directory: "目錄",
        Files_Delete_Title: "刪除這些文件？",
        Files_Delete_Desc_1: "您確定想要刪除{{selected}}文件？",
        Files_Delete_Desc_2: "刪除下方列出的文件是一項永久性操作，您不能撤銷這個操作。",
        Files_Delete_Desc_3: "其他",
        Files_Delete_Button: "是，刪除文件",
        Files_SubMenu_Rename: "重命名",
        Files_SubMenu_Move: "移動",
        Files_SubMenu_Permissions: "權限",
        Files_SubMenu_Copy: "複製",
        Files_SubMenu_Archive: "壓縮",
        Files_SubMenu_Unarchive: "解壓縮",
        Files_SubMenu_Download: "下載",
        Files_SubMenu_Delete: "刪除",
        Files_Edit_Ptero_Ignore_1: "您正在編輯一個",
        Files_Edit_Ptero_Ignore_2: "文件。此處列出的任何文件或目錄都將從備份中排除。支持透過星號使用通配符",
        Files_Edit_Ptero_Ignore_3: "您可以透過在句子前面加上驚嘆號來使規則失效",
        Files_Edit_Save_Button: "保存更改",
        Files_Create_Title: "檔案名稱",
        Files_Create_Desc: "輸入這個文件應該被保存為的名稱。",
        Files_Create_Error: "檔案名是必填欄位",
        Files_Create_Button: "新增文件",
        Files_Message_Archiving: "壓縮檔案中",
        Files_Message_Deleting: "刪除文件...",
        Files_Create_Directory_Title: "目錄名稱",
        Files_Create_Directory_Desc_1: "必須提供有效的目錄名稱。",
        Files_Create_Directory_Desc_2: "該目錄將被創建為",
        Files_Create_Directory_Button: "新增目錄",
        Files_Move_Desc_1: "輸入這個文件或文件夾的新名稱和路徑，相對於當前目錄。",
        Files_Move_Desc_2: "新位置：",
        Files_Drag_Desc: "拖放文件以上傳。",
        Files_Drag_Button: "上傳",
        Files_Error_1: "需要檔案名。",
        Files_Error_2: "遠程主機上發生錯誤：無法移動或重命名文件，目標已存在.."
      },
      Server_Users: {
        User_Page_Title: "用戶",
        User_Sub_Users_Empty: "您似乎沒有任何子用戶。",
        User_Create_Title_1: "創建新子用戶",
        User_Create_Title_2: "用戶信箱",
        User_Create_Sub_User_Desc_1: "輸入您希望邀請作為此伺服器子用戶的用戶的電子郵件地址。",
        User_Create_Sub_User_Desc_2: "電子郵件地址不得超過 191 個字元。",
        User_Create_Sub_User_Desc_3: "必須提供有效的電子郵件地址。",
        User_Modify_Or_View_Email_Title: "給{{subuser}}的權限",
        User_Modify_Title: "Modify",
        User_View_Title: "View",
        User_Modify_Button: "保存",
        User_Create_Button_1: "邀請用戶",
        User_Create_Button_2: "新用戶",
        User_Create_Sub_User_Desc: "在創建或修改其他用戶時，只能選擇您的帳戶當前分配的權限。",
        User_Delete_Title: "刪除這個子用戶？",
        User_Delete_Desc_1: "您確定要刪除這個子用戶嗎？他們將會被立即撤銷對該伺服器的所有訪問權限。",
        User_Delete_Button: "是，刪除子用戶",
        User_Show_2FA: "已啟用二次身份驗證",
        User_Show_Permissions: "權限",
        User_Create_Sub_Title_1: "伺服器控制",
        User_Create_Sub_Title_2: "用戶",
        User_Create_Sub_Title_3: "文件",
        User_Create_Sub_Title_4: "備份",
        User_Create_Sub_Title_5: "網路設定",
        User_Create_Sub_Title_6: "啟動設定",
        User_Create_Sub_Title_7: "資料庫",
        User_Create_Sub_Title_8: "伺服器進程",
        User_Create_Sub_Title_9: "設置",
        User_Create_Desc_1: "允許用戶控制伺服器電源狀態或使用命令。",
        User_Create_Desc_2: "允許用戶管理伺服器上的其他子用戶。 他們永遠無法編輯自己的帳戶，或分配自己沒有的權限。",
        User_Create_Desc_3: "允許控制用戶修改此伺服器的文件系統的能力。",
        User_Create_Desc_4: "允許控制用戶生成和管理伺服器備份的能力。",
        User_Create_Desc_5: "允許控制用戶修改此伺服器分配的埠的能力。",
        User_Create_Desc_6: "允許that control a user's ability to view this server's startup parameters.",
        User_Create_Desc_7: "允許that control a user's access to the database management for this server.",
        User_Create_Desc_8: "允許that control a user's access to the schedule management for this server.",
        User_Create_Desc_9: "允許that control a user's access to the settings for this server.",
        User_Create_Option_Desc_1: "控制台",
        User_Create_Option_Desc_2: "啟動",
        User_Create_Option_Desc_3: "停止",
        User_Create_Option_Desc_4: "重啟",
        User_Create_Option_Desc_5: "創建",
        User_Create_Option_Desc_6: "讀取",
        User_Create_Option_Desc_7: "上傳",
        User_Create_Option_Desc_8: "刪除",
        User_Create_Option_Desc_9: "Read-content",
        User_Create_Option_Desc_10: "壓縮",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "下載",
        User_Create_Option_Desc_13: "恢復",
        User_Create_Option_Desc_14: "Docker鏡像",
        User_Create_Option_Desc_15: "檢視密碼",
        User_Create_Option_Desc_16: "重命名",
        User_Create_Option_Desc_17: "重新安裝",
        User_Create_Option_Description_1: "允許用戶通過控制台向伺服器實例發送命令。",
        User_Create_Option_Description_2: "允許用戶在伺服器停止時啟動它。",
        User_Create_Option_Description_3: "允許用戶停止正在運行的伺服器。",
        User_Create_Option_Description_4: "允許用戶執行伺服器重啟。 這允許他們在離線時啟動伺服器，但不會將伺服器置於完全停止狀態。",
        User_Create_Option_Description_5: "允許用戶為伺服器創建新的子用戶。",
        User_Create_Option_Description_6: "允許用戶查看子用戶及其對伺服器的權限。",
        User_Create_Option_Description_7: "允許用戶修改其他子用戶。",
        User_Create_Option_Description_8: "允許用戶從伺服器中刪除子用戶。",
        User_Create_Option_Description_9: "允許用戶通過面板或直接上傳創建其他文件和文件夾。",
        User_Create_Option_Description_10: "允許用戶查看目錄的內容，但不能查看或下載文件的內容。",
        User_Create_Option_Description_11: "允許用戶查看給定文件的內容。 這也將允許用戶下載文件。",
        User_Create_Option_Description_12: "允許用戶更新現有文件或目錄的內容。",
        User_Create_Option_Description_13: "允許用戶刪除文件或目錄。",
        User_Create_Option_Description_14: "Allows a user to archive the contents of a directory as well as decompress existing archives on the system.",
        User_Create_Option_Description_15: "允許用戶連接到 SFTP 並使用其他檔案管理器管理伺服器文件。",
        User_Create_Option_Description_16: "允許用戶為此伺服器創建新備份。",
        User_Create_Option_Description_17: "允許用戶查看此伺服器存在的所有備份。",
        User_Create_Option_Description_18: "允許用戶從系統中刪除備份。",
        User_Create_Option_Description_19: "允許用戶下載伺服器的備份。警告：這允許用戶訪問伺服器備份中的所有文件。",
        User_Create_Option_Description_20: "允許用戶從備份恢復伺服器。警告：這允許用戶在此過程中刪除所有伺服器文件。",
        User_Create_Option_Description_21: "Allows a user to view all allocations currently assigned to this server. Users with any level of access to this server can always view the primary allocation.",
        User_Create_Option_Description_22: "Allows a user to assign additional allocations to the server.",
        User_Create_Option_Description_23: "Allows a user to change the primary server allocation and attach notes to each allocation.",
        User_Create_Option_Description_24: "Allows a user to delete an allocation from the server.",
        User_Create_Option_Description_25: "允許用戶查看伺服器的啟動變數。",
        User_Create_Option_Description_26: "允許用戶修改伺服器的啟動變數。",
        User_Create_Option_Description_27: "允許用戶修改運行伺服器時使用的 Docker 鏡像。",
        User_Create_Option_Description_28: "允許用戶為此伺服器創建新資料庫。",
        User_Create_Option_Description_29: "允許用戶查看與該伺服器相關聯的資料庫。",
        User_Create_Option_Description_30: "Allows a user to rotate the password on a database instance. If the user does not have the view_password permission they will not see the updated password.",
        User_Create_Option_Description_31: "允許用戶從此伺服器中刪除資料庫實例。",
        User_Create_Option_Description_32: "允許用戶查看與該伺服器的資料庫實例相關聯的密碼。",
        User_Create_Option_Description_33: "允許用戶創建新進程.",
        User_Create_Option_Description_34: "Allows a user to view schedules and the tasks associated with them for this server.",
        User_Create_Option_Description_35: "允許用戶調整進程",
        User_Create_Option_Description_36: "允許用戶刪除進程",
        User_Create_Option_Description_37: "允許用戶重命名此伺服器。",
        User_Create_Option_Description_38: "允許用戶重新安裝此伺服器。"
      },
      Server_Network: {
        Network_Page_Title: "網路",
        Network_Alocations_Desc_1: "You are currently using {{data}} of {{limit}} allowed allocations for this server.",
        Network_Create_Alocation_Button: "Create Allocation",
        Network_Hostname: "網址名稱",
        Network_IP_Address: "IP位址",
        Network_Port: "埠",
        Network_Notes: "備註",
        Network_Primary: "Primary",
        Network_Primary_Button: "Make Primary",
        Network_Delete_Title: "刪除此分配？",
        Network_Delete_Button: "刪除",
        Network_Delete_Desc_1: "This allocation will be immediately removed from your server. Are you sure you want to continue?",
        Network_Error_1: "Server auto-allocation is not enabled for this instance.",
      },
      Server_Schedules: {
        Task_Page_Title: "Schedules",
        Task_Empty_Message: "There are no schedules configured for this server.",
        Task_Create_Button: "Create schedule",
        Task_Edit_Button: "保存更改",
        Task_Delete_Title: "Delete schedule?",
        Task_Delete_Button_1: "Yes, delete schedule",
        Task_Delete_Desc: "Are you sure you want to delete this schedule? All tasks will be removed and any running processes will be terminated.",
        Task_Delete_Button_2: "刪除",
        Task_Create_Title: "Create new schedule",
        Task_Edit_Title: "Edit schedule",
        Task_Create_Or_Edit_Title_1: "Schedule name",
        Task_Create_Or_Edit_Title_2: "僅當伺服器在線時",
        Task_Create_Or_Edit_Title_3: "Schedule Enabled",
        Task_Create_Or_Edit_Desc_1: "A human readable identifer for this schedule.",
        Task_Create_Or_Edit_Desc_2: "The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.",
        Task_Create_Or_Edit_Desc_3: "Only execute this schedule when the server is in a running state.",
        Task_Create_Or_Edit_Desc_4: "This schedule will be executed automatically if enabled.",
        Task_Create_Or_Edit_Minute: "Minute",
        Task_Create_Or_Edit_Hour: "小時",
        Task_Create_Or_Edit_Day_Of_Month: "Day of month",
        Task_Create_Or_Edit_Month: "月",
        Task_Create_Or_Edit_Day_Of_Week: "Day of week",
        Task_New_Task_Button: "New Task",
        Task_Run_Task_Button: "現在運行",
        Task_Cron_Row_Minute: "分鐘",
        Task_Cron_Row_Hour: "小時",
        Task_Cron_Row_Day_Month: "Day (Month)",
        Task_Cron_Row_Month: "月",
        Task_Cron_Row_Day_Week: "Day (Week)",
        Task_Task_Page_Title: "Tasks",
        Task_Task_Processing: "Processing",
        Task_Task_Last_Run: "Last run at:",
        Task_Task_Next_Run: "Next run at:",
        Task_Task_Never: "永不",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "編輯",
        Task_Task_Active: "Active",
        Task_Task_Inactive: "Inactive",
        Task_Task_Delete_Title: "Confirm task deletion",
        Task_Task_Delete_Button: "Delete Task",
        Task_Task_Delete_Desc: "Are you sure you want to delete this task? This action cannot be undone.",
        Task_Task_Files_And_Folders_Message: "Ignoring files & folders:",
        Task_Task_Continue_Message: "Continues on Failure",
        Task_Task_Time_Message: "{{time}}s later",
        Task_Task_Edit_Title: "Edit Task",
        Task_Task_Create_Title: "Create Task",
        Task_Task_Create_Or_Edit_Command: "發送命令",
        Task_Task_Create_Or_Edit_Power: "發送電源操作",
        Task_Task_Create_Or_Edit_Backup: "創建備份",
        Task_Task_Create_Or_Edit_Title_1: "Time offset (in seconds)",
        Task_Task_Create_Or_Edit_Title_2: "Payload",
        Task_Task_Create_Or_Edit_Title_3: "忽略的文件",
        Task_Task_Create_Or_Edit_Title_4: "Continue on Failure",
        Task_Task_Create_Or_Edit_Title_5: "Action",
        Task_Task_Create_Or_Edit_Desc_1: "The amount of time to wait after the previous task executes before running this one. If this is the first task on a schedule this will not be applied.",
        Task_Task_Create_Or_Edit_Desc_2: "Optional. Include the files and folders to be excluded in this backup. By default, the contents of your .pteroignore file will be used. If you have reached your backup limit, the oldest backup will be rotated.",
        Task_Task_Create_Or_Edit_Desc_3: "Future tasks will be run when this task fails.",
        Task_Task_Create_Or_Edit_Option_1: "啟動伺服器",
        Task_Task_Create_Or_Edit_Option_2: "重啟伺服器",
        Task_Task_Create_Or_Edit_Option_3: "停止伺服器",
        Task_Task_Create_Or_Edit_Option_4: "終止伺服器",
        Task_Task_Create_Or_Edit_Error_1: "A task payload must be provided.",
        Task_Task_Create_Or_Edit_Error_2: "The time offset must be a valid number between 0 and 900.",
        Task_Task_Create_Or_Edit_Error_3: "A time offset value must be provided.",
        Task_Task_Create_Or_Edit_Error_4: "The time offset must be at least 0 seconds.",
        Task_Task_Create_Or_Edit_Error_5: "The time offset must be less than 900 seconds.",
        Task_Task_Create_Or_Edit_Error_6: "當伺服器的備份限制設置為 0 時，無法創建備份任務。"
      },
      Server_Settings: {
        Settings_Page_Title: "設置",
        Settings_SFTP_Title_1: "SFTP詳情",
        Settings_SFTP_Title_2: "伺服器地址",
        Settings_SFTP_Title_3: "使用者名稱",
        Settings_SFTP_Desc_1: "您的SFTP密碼與您用於訪問此面板的密碼相同。",
        Settings_SFTP_Button: "運行SFTP",
        Settings_Debug_Title_1: "除錯訊息",
        Settings_Debug_Title_2: "節點",
        Settings_Debug_Title_3: "伺服器ID",
        Settings_Reinstall_Title_1: "重新安裝伺服器",
        Settings_Reinstall_Title_2: "確認重新安裝伺服器",
        Settings_Reinstall_Button: "是，重新安裝伺服器",
        Settings_Reinstall_Desc_1: "在此過程中，您的伺服器將停止運行，並且可能會刪除或修改某些文件，您確定要繼續嗎？",
        Settings_Reinstall_Desc_2: "重新安裝伺服器將停止它，然後重新運行最初設置它的安裝腳本。",
        Settings_Reinstall_Desc_3: "在此過程中可能會刪除或修改某些文件，請在繼續操作之前備份您的數據。",
        Settings_Reinstall_Success: "您的伺服器已開始重新安裝進程。",
        Settings_Reinstall_Error: "無法與運行此伺服器的計算機建立連接。請稍後重試",
        Settings_Rename_Server_Title_1: "修改伺服器名稱",
        Settings_Rename_Server_Title_2: "伺服器名稱",
        Settings_Rename_Server_Button: "保存",
        Settings_Rename_Required: "名稱是必填欄位"
      },
      Server_Startup: {
        Startup_Page_Title: "啟動設置",
        Startup_Command_Title_1: "啟動命令",
        Startup_Docker_Title: "Docker鏡像",
        Startup_Docker_Desc: "這是一項進階功能，允許您在運行此伺服器實例時選擇要使用的 Docker 映像。",
        Startup_Docker_Error: "此伺服器的 Docker 映像已由管理員手動設置，無法通過此 UI 更改。",
        Startup_Variables_Title: "啟動參數",
        Startup_Variables_Read: "只讀",
        Startup_Server_Error_Title: "Oops!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "無效的Java版本，更新 Docker 鏡像？",
        Features_Invalid_Java_Desc_1: "由於Java版本不滿足要求，此伺服器無法啟動。",
        Features_Invalid_Java_Desc_2: `通過按下面的"更新 Docker 鏡像"，您確認此伺服器使用的 Docker 鏡像將更改為下麵包含您請求的 Java 版本的鏡像。`,
        Features_Invalid_Java_Desc_3: "請從下面的列表中選擇一個 Java 版本。",
        Features_Invalid_Java_Button_1: "更新 Docker 鏡像",
        Features_Invalid_Java_Button_2: "取消",
        Features_Accept_Eula_Title: "同意Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `點擊下方的"我同意"即表示您同意`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "我同意",
        Features_Accept_Eula_Button_2: "取消",
      },
      Server_States: {
        Server_Installing_Title: "安裝中",
        Server_Installing_Desc: "您的伺服器馬上就準備好，請在幾分鐘後重試。",
        Server_Suspended_Title: "伺服器已暫停",
        Server_Suspended_Desc: "此伺服器已被暫停且不可訪問。",
        Server_Transferring_Title: "遷移中",
        Server_Transferring_Desc: "您的伺服器已經遷移到一個新的節點，請在稍後查看。",
        Server_Restoring_Title: "從備份中恢復",
        Server_Restoring_Desc: "您的伺服器當前正在從一個備份中恢復，請在幾分鐘後查看。"
      },
      Page_Titles: {
        Title_Console: "控制台",
        Title_File_Manager: "檔案管理器",
        Title_Databases: "資料庫",
        Title_Schedules: "進程",
        Title_Users: "用戶",
        Title_Backups: "備份",
        Title_Network: "網路",
        Title_Startup: "啟動",
        Title_Settings: "設置",
        Title_API_Credentials: "API證書"
      },
      Times_And_Dates: {
        Date_Format: "dd'-'MM'-'yyyy h:mma", // For details about formats, look at this: https://thecodebarbarian.com/formatting-javascript-dates-with-moment-js.html
        Time_Minutes_1: "3分鐘前",
        Time_Minutes_2: "2分鐘前",
        Time_Minutes_3: "1分鐘前",
        Time_Minutes_4: "少於1分鐘",
        Time_Minutes_5: "不到1分鐘前",
        Time_Minutes_6: "1分鐘前",
        Time_Minutes_7: "2分鐘前",
        Time_Minutes_8: "3分鐘前",
        Time_Minutes_9: "4分鐘前",
        Time_Minutes_10: "5分鐘前",
        Time_Minutes_11: "6分鐘前",
        Time_Minutes_12: "7分鐘前",
        Time_Minutes_13: "8分鐘前",
        Time_Minutes_14: "9分鐘前",
        Time_Minutes_15: "10分鐘前",
        Time_Minutes_16: "11分鐘前",
        Time_Minutes_17: "12分鐘前",
        Time_Minutes_18: "13分鐘前",
        Time_Minutes_19: "14分鐘前",
        Time_Minutes_20: "15分鐘前",
        Time_Minutes_21: "16分鐘前",
        Time_Minutes_22: "17分鐘前",
        Time_Minutes_23: "18分鐘前",
        Time_Minutes_24: "19分鐘前",
        Time_Minutes_25: "20分鐘前",
        Time_Minutes_26: "21分鐘前",
        Time_Minutes_27: "22分鐘前",
        Time_Minutes_28: "23分鐘前",
        Time_Minutes_29: "24分鐘前",
        Time_Minutes_30: "25分鐘前",
        Time_Minutes_31: "26分鐘前",
        Time_Minutes_32: "27分鐘前",
        Time_Minutes_33: "28分鐘前",
        Time_Minutes_34: "29分鐘前",
        Time_Minutes_35: "30分鐘前",
        Time_Minutes_36: "31分鐘前",
        Time_Minutes_37: "32分鐘前",
        Time_Minutes_38: "33分鐘前",
        Time_Minutes_39: "34分鐘前",
        Time_Minutes_40: "35分鐘前",
        Time_Minutes_41: "36分鐘前",
        Time_Minutes_42: "37分鐘前",
        Time_Minutes_43: "38分鐘前",
        Time_Minutes_44: "39分鐘前",
        Time_Minutes_45: "40分鐘前",
        Time_Minutes_46: "41分鐘前",
        Time_Minutes_47: "42分鐘前",
        Time_Minutes_48: "43分鐘前",
        Time_Minutes_49: "44分鐘前",
        Time_Minutes_50: "45分鐘前",
        Time_Minutes_51: "46分鐘前",
        Time_Minutes_52: "47分鐘前",
        Time_Minutes_53: "48分鐘前",
        Time_Minutes_54: "49分鐘前",
        Time_Minutes_55: "50分鐘前",
        Time_Minutes_56: "51分鐘前",
        Time_Minutes_57: "52分鐘前",
        Time_Minutes_58: "53分鐘前",
        Time_Minutes_59: "54分鐘前",
        Time_Minutes_60: "55分鐘前",
        Time_Minutes_61: "56分鐘前",
        Time_Minutes_62: "57分鐘前",
        Time_Minutes_63: "58分鐘前",
        Time_Minutes_64: "59分鐘前",
        Time_Hours_1: "1小時前",
        Time_Hours_2: "2小時前",
        Time_Hours_3: "3小時前",
        Time_Hours_4: "4小時前",
        Time_Hours_5: "5小時前",
        Time_Hours_6: "6小時前",
        Time_Hours_7: "7小時前",
        Time_Hours_8: "8小時前",
        Time_Hours_9: "9小時前",
        Time_Hours_10: "10小時前",
        Time_Hours_11: "11小時前",
        Time_Hours_12: "12小時前",
        Time_Hours_13: "13小時前",
        Time_Hours_14: "14小時前",
        Time_Hours_15: "15小時前",
        Time_Hours_16: "16小時前",
        Time_Hours_17: "17小時前",
        Time_Hours_18: "18小時前",
        Time_Hours_19: "19小時前",
        Time_Hours_20: "20小時前",
        Time_Hours_21: "21小時前",
        Time_Hours_22: "22小時前",
        Time_Hours_23: "23小時前",
      },
      Errors: {
        Error_Key_Undefined: "翻譯錯誤：這個訊息並沒有被設定, 請聯絡: Ferks#7575",
        Error_Server_Title: "出了點問題",
        Error_Server_Desc: "The requested resource was not found.",
        Error_Permission_Title: "訪問被拒絕",
        Error_Permission_Desc: "您沒有權限訪問此頁面。",
        Error_Variables_1: "The value field is required.",
        Error_Variables_2: "The value must be 1 digits.",
        Error_Variables_3: "This value is not valid.",
        Error_Variables_4: "The value must be at least 1.",
        Error_Variables_5: "This value is greater than the limit.",
        Error_Variables_6: "The value format is invalid.",
        Error_Variables_7: "The value may only contain letters, numbers, and dashes."
      },
    }
}
